# Config file for automatic testing at travis-ci.org

dist: focal
sudo: required
language: python
python: 3.8
services:
  - postgresql

addons:
  postgresql: "9.4"

env:
  - TOX_ENV=py38-django-31
  - TOX_ENV=py37-django-31
  - TOX_ENV=py36-django-31
  - TOX_ENV=py38-django-30
  - TOX_ENV=py37-django-30
  - TOX_ENV=py36-django-30

matrix:
  fast_finish: true

install: pip install -r requirements-test.txt

script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV

#deploy:
#  provider: pypi
#  user: $PYPI_USER
#  password:
#    secure: $PYPI_PASSWORD
#  on:
#    repo: GoVanguard/django-auditlog
#    branch: stable
#    condition: $TOX_ENV = py38-django-31
